- name: Install nginx for Redhat
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy the expense.conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: import the role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq.yml

- name: enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true